apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: basic-es
  namespace: logging
spec:
  version: 7.10.1
  nodeSets:
  - name: master
    count: 1
    config:
      node.roles: ["master"]
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
  - name: ingest-data
    count: 1
    config:
      node.roles: ["data", "ingest"]
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          #alternative is to set it on host: https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: logging
spec:
  version: 7.10.1
  count: 1
  elasticsearchRef:
    name: "basic-es"
  http:
    tls:
      selfSignedCertificate:
        disabled: true