

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test
  region: us-east-2

nodeGroups:
- name: cpu-workers-base
  labels:
    worker: main
  tags:
    Project: CV
  instanceType: t3.xlarge
  desiredCapacity: 1
  minSize: 0
  maxSize: 5
  privateNetworking: true
  iam:
    withAddonPolicies:
      autoScaler: true
  kubeletExtraConfig:
    kubeReserved:
        cpu: "300m"
        memory: "300Mi"
        ephemeral-storage: "1Gi"
    kubeReservedCgroup: "/kube-reserved"
    systemReserved:
        cpu: "300m"
        memory: "300Mi"
        ephemeral-storage: "1Gi"
    evictionHard:
        memory.available:  "200Mi"
        nodefs.available: "10%"
    featureGates:
        DynamicKubeletConfig: true
        RotateKubeletServerCertificate: true
- name: gpu-nodes-two
  instanceType: g4dn.xlarge	
  labels:
    worker: gpu
  desiredCapacity: 0
  minSize: 0
  maxSize: 5
  privateNetworking: true
  iam:
    withAddonPolicies:
      autoScaler: true
  kubeletExtraConfig:
    kubeReserved:
        cpu: "300m"
        memory: "300Mi"
        ephemeral-storage: "1Gi"
    kubeReservedCgroup: "/kube-reserved"
    systemReserved:
        cpu: "300m"
        memory: "300Mi"
        ephemeral-storage: "1Gi"
    evictionHard:
        memory.available:  "200Mi"
        nodefs.available: "10%"
    featureGates:
        DynamicKubeletConfig: true
        RotateKubeletServerCertificate: true